# Je pense que non car

## Premiere fonction lireDesFichiersForTry()
Le try-catch est dans le for donc même si une exeption est lever la lecture vas continuer pour les autre.

## Deuxième fonction lireDesFichiersTryFor()
Le try-catch est a l'extérieur du for donc si un fichier lève l'exeption le for vas arréter 